import * as React from 'react';
import {PageLayout} from "../common";

type Props = {};

export function Home(props: Props) {
    return (
        <PageLayout>
            <h1>Home</h1>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos maxime sapiente ut? Aperiam corporis culpa, cum, cupiditate deleniti in ipsa mollitia perspiciatis quidem, quos repellendus similique sint suscipit tenetur vel.</span><span>Ab aperiam dolore ex incidunt magnam maxime nulla obcaecati officiis sunt temporibus. Ea enim error minima rem sequi sint vero. Consequuntur doloribus eius est ipsam molestiae nam recusandae rem tempora.</span><span>Aperiam cupiditate, dolorem ducimus ex expedita odio sed voluptatem! Cum dolorum eos eum exercitationem laborum non quam, quas qui ratione rem, repellendus saepe sequi similique tempora unde velit voluptate voluptatibus.</span><span>Aliquid amet architecto aut beatae cupiditate deleniti dignissimos dolor dolorum earum, error in incidunt inventore maiores, necessitatibus, quod ratione recusandae repellat repellendus rerum tempore? Dicta hic iure molestiae optio repellendus?</span><span>Beatae enim magnam nulla praesentium quis. Consectetur facilis illo itaque labore nemo officia omnis velit veniam veritatis. Aspernatur eaque enim facilis harum laudantium minus mollitia porro quam quasi, voluptatibus voluptatum?</span><span>Atque consectetur, deleniti eligendi exercitationem iste libero omnis sint tempora. Architecto commodi debitis dolorem eum exercitationem fugit modi nisi omnis qui sunt, totam ullam ut voluptas. Incidunt magnam maiores recusandae?</span><span>Blanditiis delectus doloribus eligendi et qui quidem repellendus voluptate! Alias autem doloremque dolorum, earum esse est facilis itaque, minima, molestiae quae reprehenderit sit. Cupiditate est harum hic iure magni, minima.</span><span>Dolor eligendi eos fuga in laborum omnis! Architecto, culpa doloribus exercitationem maiores quasi quisquam sed? Aspernatur at, corporis, deserunt dolorem doloremque ducimus fugiat nihil officia quaerat quia quibusdam repudiandae, tempore.</span><span>Adipisci, distinctio dolore dolorem ducimus fugit laborum minima omnis! Accusamus adipisci corporis laborum nesciunt numquam officiis repudiandae voluptates. Alias deleniti eligendi impedit maiores recusandae. A atque dolorem excepturi natus sequi!</span><span>Aut beatae, dolorum eos praesentium quaerat quas quia rerum ullam vel voluptatum! Aliquid amet asperiores, assumenda autem cumque dolores eius, eligendi est fuga labore non, porro quidem quos ratione reiciendis.</span>
            </p>
        </PageLayout>
    );
}